on:
  push:
    branches:
      - '*'
      - '!master'
      - '!develop'
      - '!feature/*'
      - '!hotfix/*'
      - '!release/*'

jobs:
  build:
    name: Branch name check (non-Gitflow)
    runs-on: ubuntu-latest
    steps:
      - name: Branch name doesn't match Gitflow
        run: exit 1
