on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish npm packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Lerna CLI
        run: npm i -g lerna

      - name: Link local packages together and install remaining package dependencies
        run: lerna bootstrap

      - name: Set the token for publishing to npm
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set lerna version --yes
        run: lerna version patch

      - name: Publish npm package
        run: lerna publish --yes
