on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Link local packages together and install remaining package dependencies
        uses: lerna bootstrap

      - name: Import the package in the local path
        uses: lerna import ./packages/eslint-config

      - name: Publish npm package
        uses: lerna publish
