on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish npm packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Set the token for publishing to npm
        run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc

      - name: Install Lerna CLI
        run: npm i -g lerna

      - name: Publish npm package
        run: lerna publish from-package --yes
